version: '3.8'

services:
    app:
        build:
            context: .
            target: production
        container_name: todo-app
        ports:
            - 8080:8080
        working_dir: /app
        env_file:
            - ./.env
        environment:
            PSQL_HOST: $PSQL_HOST
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB
            NODE_ENV: "prod"
        depends_on:
            - 'psql'

    psql:
        image: postgres:14
        container_name: psql-db
        volumes:
            - todo-psql-data:/var/lib/postgresql/data
        env_file:
            - ./.env
        environment:
            POSTGRES_USER: $POSTGRES_USER
            POSTGRES_PASSWORD: $POSTGRES_PASSWORD
            POSTGRES_DB: $POSTGRES_DB

volumes:
    todo-psql-data:
