- name: Docker installation with SonarQube
  hosts: localhost
  # hosts: test_servers
  become: yes
  tasks:
    - name: Update and install dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
        - docker-ce

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Set up the stable repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update Cache
      apt:
        update_cache: yes

    - name: Start and enable Docker service
      systemd:
        name: docker
        enabled: yes
        state: started

    - name: Pull SonarQube Docker image
      ansible.builtin.command: docker pull sonarqube:latest

    - name: Run SonarQube container
      command: docker run -d --name sonarqube -p 9000:9000 sonarqube:latest

    - name: Allow traffic on port 9000
      command: iptables -A INPUT -p tcp --dport 9000 -j ACCEPT

    - name: Forward port 9000 on host to the Docker container
      command: iptables -t nat -A PREROUTING -p tcp --dport 9000 -j DNAT --to-destination 172.17.0.2:9000
      args:
        warn: false

    - name: Allow forwarded traffic on the Docker bridge network
      command: iptables -t nat -A POSTROUTING -j MASQUERADE
      args:
        warn: false

    - name: Save iptables rules
      command: iptables-save > /etc/iptables/rules.v4
      args:
        warn: false

    - name: Ensure netfilter-persistent is installed
      apt:
        name: netfilter-persistent
        state: present

    - name: Reload netfilter-persistent to apply rules
      command: netfilter-persistent reload
