# # version: '3.8'

# # services:
# #   app:
# #     build:
# #       context: .
# #       target: development
# #     container_name: todo-app-testing-jest
# #     ports:
# #       - 8090:8090"
# #     working_dir: /app
# #     volumes:
# #       - ./app:/app
# #       - /app/node_modules
# #     env_file:
# #       - ./.env
# #     environment:
# #       PSQL_HOST: ${PSQL_HOST}
# #       POSTGRES_USER: ${POSTGRES_USER}
# #       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
# #       POSTGRES_DB: ${POSTGRES_DB}
# #       NODE_ENV: "dev"
# #     depends_on:
# #       - psql

# #   psql:
# #     image: postgres:14
# #     container_name: psql-db-testing-jest
# #     volumes:
# #       - todo-psql-data:/var/lib/postgresql/data
# #     env_file:
# #       - ./.env
# #     environment:
# #       POSTGRES_USER: ${POSTGRES_USER}
# #       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
# #       POSTGRES_DB: ${POSTGRES_DB}

# # volumes:
# #   todo-psql-data:


# version: '3.8'

# services:
#   app:
#     build:
#       context: .
#       target: development
#     container_name: todo-app-testing-jest
#     ports:
#       - "8090:8090"
#     working_dir: /app
#     volumes:
#       - ./app:/app
#       - /app/node_modules
#     env_file:
#       - ./.env
#     environment:
#       PSQL_HOST: ${PSQL_HOST}
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}
#       NODE_ENV: "dev"
#     depends_on:
#       - psql

#   psql:
#     image: postgres:14
#     container_name: psql-db-testing-jest
#     volumes:
#       - todo-psql-data:/var/lib/postgresql/data
#     env_file:
#       - ./.env
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
#       POSTGRES_DB: ${POSTGRES_DB}

#   clair:
#     image: jasonumiker/clair:latest
#     ports:
#       - "6060:6060"
#       - "6061:6061"
#     volumes:
#       - ./clair-config.yaml:/config/config.yaml
#     environment:
#       - CLAIR_CONF=/config/config.yaml
#     depends_on:
#       - clair_postgres

#   clair_postgres:
#     image: postgres:latest
#     container_name: clair-db
#     environment:
#       POSTGRES_USER: clair
#       POSTGRES_PASSWORD: clair
#       POSTGRES_DB: clair
#     volumes:
#       - clair-postgres-data:/var/lib/postgresql/data

# volumes:
#   todo-psql-data:
#   clair-postgres-data:


version: '3.8'

services:
  app:
    build:
      context: .
      target: development
    container_name: todo-app-testing-jest
    ports:
      - "8090:8090"
    working_dir: /app
    volumes:
      - ./app:/app
      - /app/node_modules
    env_file:
      - ./.env
    environment:
      PSQL_HOST: my-postgres-host
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: polar
      POSTGRES_DB: test
      NODE_ENV: "dev"
    depends_on:
      - psql

  psql:
    image: postgres:14
    container_name: psql-db-testing-jest
    volumes:
      - todo-psql-data:/var/lib/postgresql/data
    env_file:
      - ./.env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

  clair:
    image: jasonumiker/clair:latest
    container_name: clair
    ports:
      - "7070:7070"
      - "6061:6061"
    volumes:
      - ./clair-config.yaml:/config/config.yaml
    environment:
      - CLAIR_CONF=/config/config.yaml
    depends_on:
      - clair_postgres

  clair_postgres:
    image: postgres:latest
    container_name: clair-db
    environment:
      POSTGRES_USER: clair
      POSTGRES_PASSWORD: clair
      POSTGRES_DB: clair
    volumes:
      - clair-postgres-data:/var/lib/postgresql/data

volumes:
  todo-psql-data:
  clair-postgres-data:
